### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by galenyuan** [galenyuan/vue-datatable#1]
- [x]  Search Feature
- [x]  Separate Source and Demo
- [x]  Publish to NPM
- [x] Add callback of change page
- [ ] Responsive?

**Comment by galenyuan** [comment]
挖了那么多坑也不知道自己能不能填上=。=

**Comment by warpcgd** [comment]
bug提交，搜索后，分页失效

**Comment by galenyuan** [comment]
@warpcgd 感谢，已修复
